repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-debug-statements
    -   id: no-commit-to-branch

- repo: http://github.com/psf/black
  rev: 22.12.0
  hooks:
  -   id: black
      files: \.py$