name: Run Pytest
on: push
jobs:
  run_pytest:
    name: Run Tests with Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python Env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pytest
          pip install -e .
          pip install -r requirements-test.txt
      - name: Run Pytest
        run: python -m pytest
      
    
